all:
  children:
    webserver:
      hosts:
        web01:
          ansible_host: 44.215.110.38
    dbserver:
      hosts:
        db01:
          ansible_host: 3.235.88.17
    dc_ohio:
      children:
        webserver:
        dbserver:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: web-dev-key.pem

