---
- name: Setup DBserver
  hosts: dbserver
  become: yes
  vars:
    dbname: sky
    dbuser: pilot
    dbpass: aircraft

  tasks:
    - name: Install MySQL server
      yum:
         name: mariadb-server
         state: present
         
    - name: Install Python MySQL 
      ansible.builtin.yum:
         name: python3-PyMySQL
         state: present

    - name: Start & Enable maridb service
      service:
         name: mariadb
         state: started
         enabled: yes

    - name: Create a new database with name 'accounts'
      mysql_db:
        name: accounts
        state: present

    - name: Create database user with name 'admin' 
      mysql_user:
        name: admin
        password: 12345
        priv: '*.*:ALL'
        state: present
