---
- name: Provision EC2 Instance
  hosts: localhost
  remote_user: ec2-user
  become: yes
  gather_facts: False
  tasks:
    - name: Include AWS credentials
      include_vars: aws_credentials.yml

    - name: Create EC2 instance
      ec2_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "web-dev-key"
        instance_type: t3.micro
        image: 
          id: "ami-0df2a11dd1fe1f8e3"
        region: us-east-1
        security_groups: sg-0889aea08fd828811
        count: 1
        wait: yes
        tags:
          Name: AnsibleInstance
      register: ec2

    - name: Display instance information
      debug:
        var: ec2.instances[0]

- name: Configure EC2 Instance
  hosts: launched
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Update yum cache
      yum:
        name: "*"
        state: latest

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes