---
- name: Provision EC2 Instance
  hosts: localhost
  remote_user: ec2-user
  become: yes
  gather_facts: False
  tasks:
    - name: Start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "Launched by Ansible"
        key_name: "web-dev-key"
        aws_access_key: AKIA3XEVJO34CUXRYFP3
        aws_secret_key: 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
        instance_type: t3.micro
        security_group: default
        region: us-east-1
        network:
          assign_public_ip: true
        image_id: ami-0df2a11dd1fe1f8e3
        count: 1
        wait: yes
        tags:
          Name: AnsibleInstance

    - name: Upgrade all packages, excluding kernel & foo related packages
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: kernel*,foo*

    - name: Install Apache
      package:
        name: httpd
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes